export const DOCS_REFERENCES = {
    errors: "https://docs.x.immutable.com/docs/link-errors",
    setup: "https://docs.x.immutable.com/docs/link-setup",
    deposit: "https://docs.x.immutable.com/docs/link-deposit-options",
    fiatToCrypto: "https://docs.x.immutable.com/docs/link-fiat-to-crypto",
    prepareWithdrawal: "https://docs.x.immutable.com/docs/linkpreparewithdrawal",
    completeWithdrawal: "https://docs.x.immutable.com/docs/linkcompletewithdrawal",
    cryptoToFiat: "https://docs.x.immutable.com/docs/link-crypto-to-fiat",
    sell: "https://docs.x.immutable.com/docs/linksell-and-erc20-support",
    cancel: false,
    buy: "https://docs.x.immutable.com/docs/link-buy2",
    makeOffer: "https://docs.x.immutable.com/docs/link-make-offer",
    cancelOffer: "https://docs.x.immutable.com/docs/link-cancel-offer",
    acceptOffer: "https://docs.x.immutable.com/docs/link-accept-offer",
    nftCheckoutPrimary: "https://docs.x.immutable.com/docs/link-nft-checkout-primary",
    batchNftTransfer: "https://docs.x.immutable.com/docs/linkbatchnfttransfer",
    transfer: "https://docs.x.immutable.com/docs/linktransfer",
    history: false,
    sign: "https://docs.x.immutable.com/docs/linksign",
    getPublicKey: "https://docs.x.immutable.com/docs/linksign/#encryption-public-key",
}